version: "3"
services:
  phone_dict_gen:
    build:
      context: .
      dockerfile: Dockerfile
    # container_name: phone_dict_gen
    volumes:
      - ./temp:/app/temp
      - ./logs:/app/logs
    # restart: unless-stopped
